name: Build, test and deploy

on:
  push:
    branches:
      - master

env:
  NODE_VERSION: 20.x
  ENTRY_FILE: 'src/aberdeen.ts'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm ci
      - name: Build docs
        run: npm run build && cp -rav examples dist docs/
      - name: Upload docs artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'
      - name: Deploy docs to GitHub Pages
        uses: actions/deploy-pages@v4
      - name: Test, build and deploy code to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
