name: Build, test and deploy

on:
  push:
    branches:
      - master

env:
  NODE_VERSION: 20.x
  ENTRY_FILE: 'src/aberdeen.ts'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Build docs
        run: npm run build && cp -ra examples dist dist-docs/
      - name: Upload docs artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist-docs'
      - name: Deploy docs to GitHub Pages
        uses: actions/deploy-pages@v4
      - name: Test, build and deploy code to NPM
        run: |
          output=$(bun publish --access=public 2>&1); ec=$?
          echo "$output"
          if [ "$ec" -ne 0 ] && [[ "$output" == *"You cannot publish over the previously published versions"* ]]; then
            echo "Version already published. Considering this a success."
            exit 0
          fi
          exit "$ec"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
